src/Entity/Assureur.php
<?php

namespace App\Entity;

use App\Repository\AssureurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AssureurRepository::class)
 */
class Assureur
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="integer")
     */
    private $cin_assureur;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min = 4,
     *      max = 20,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $mail;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotEqualTo("00000000")
     * @Assert\NotBlank
     */
    private $num_tel;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="assureur")
     */
    private $users;

    public function __construct()
    {
        $this->users = new ArrayCollection();
    }
/**
 * @return integer
 */
    public function getId(): ?int
    {
        return $this->id;
    }
/**
 * @return integer
 */
    public function getAge(): ?int
    {
        return $this->age;
    }
/**
 * @param integer $age
 * @return Assureur
 */
    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }
/**
 * @return integer
 */
    public function getCinAssureur(): ?int
    {
        return $this->cin_assureur;
    }
/**
 * @param string $cin_assureur
 * @return Assureur
 */
    public function setCinAssureur(int $cin_assureur): self
    {
        $this->cin_assureur = $cin_assureur;

        return $this;
    }
/**
 * @return string
 */
    public function getMail(): ?string
    {
        return $this->mail;
    }
/**
 * @param string $mail
 * @return Assureur
 */
    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }
/**
 * @return integer
 */
    public function getNumTel(): ?int
    {
        return $this->num_tel;
    }
/**
 * @param integer $num_tel
 * @return Assureur
 */
    public function setNumTel(int $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->setAssureur($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getAssureur() === $this) {
                $user->setAssureur(null);
            }
        }

        return $this;
    }
    public function __toString(){
        return $this->mail;
}
}

src/Form/AssureurType.php
<?php

namespace App\Form;

use App\Entity\Assureur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AssureurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('age')
            ->add('cin_assureur')
            ->add('mail')
            ->add('num_tel')
            ->add('users')
        
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Assureur::class,
        ]);
    }
}

src/Controller/AssureurController.php
<?php

namespace App\Controller;

use App\Entity\Assureur;
use App\Form\AssureurType;
use App\Repository\AssureurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/assureur")
 */
class AssureurController extends AbstractController
{
    /**
     * @Route("/", name="assureur_index", methods={"GET"})
     */
    public function index(AssureurRepository $assureurRepository): Response
    {
        return $this->render('assureur/index.html.twig', [
            'assureurs' => $assureurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="assureur_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $assureur = new Assureur();
        $form = $this->createForm(AssureurType::class, $assureur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($assureur);
            $entityManager->flush();

            return $this->redirectToRoute('assureur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('assureur/new.html.twig', [
            'assureur' => $assureur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="assureur_show", methods={"GET"})
     */
    public function show(Assureur $assureur): Response
    {
        return $this->render('assureur/show.html.twig', [
            'assureur' => $assureur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="assureur_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Assureur $assureur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AssureurType::class, $assureur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('assureur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('assureur/edit.html.twig', [
            'assureur' => $assureur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="assureur_delete", methods={"POST"})
     */
    public function delete(Request $request, Assureur $assureur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$assureur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($assureur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('assureur_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/assureur/_delete_form.html.twig
<form method="post" action="{{ path('assureur_delete', {'id': assureur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ assureur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/assureur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/assureur/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Edit Assureur{% endblock %}

{% block body %}
    <h1>Edit Assureur</h1>

    {{ include('assureur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('assureur_index') }}">back to list</a>

    {{ include('assureur/_delete_form.html.twig') }}
{% endblock %}

templates/assureur/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Assureur index{% endblock %}

{% block body %}
    <h1>Assureur index</h1>

    <table border="1" class="table table-hover table-dark">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Age</th>
                <th>Cin_assureur</th>
                <th>Mail</th>
                <th>Num_tel</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for assureur in assureurs %}
            <tr>
                <td>{{ assureur.id }}</td>
                <td>{{ assureur.age }}</td>
                <td>{{ assureur.cinAssureur }}</td>
                <td>{{ assureur.mail }}</td>
                <td>{{ assureur.numTel }}</td>
                <td>
                    <a href="{{ path('assureur_show', {'id': assureur.id}) }}">show</a>
                    <a href="{{ path('assureur_edit', {'id': assureur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('assureur_new') }}">Create new</a>
{% endblock %}

templates/assureur/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New Assureur{% endblock %}

{% block body %}
    <h1>Create new Assureur</h1>

    {{ include('assureur/_form.html.twig') }}

    <a href="{{ path('assureur_index') }}">back to list</a>
{% endblock %}

templates/assureur/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Assureur{% endblock %}

{% block body %}
    <h1>Assureur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ assureur.id }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ assureur.age }}</td>
            </tr>
            <tr>
                <th>Cin_assureur</th>
                <td>{{ assureur.cinAssureur }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ assureur.mail }}</td>
            </tr>
            <tr>
                <th>Num_tel</th>
                <td>{{ assureur.numTel }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('assureur_index') }}">back to list</a>

    <a href="{{ path('assureur_edit', {'id': assureur.id}) }}">edit</a>

    {{ include('assureur/_delete_form.html.twig') }}
{% endblock %}